name: CI

on:
  push:
    branches:
      - master
    paths:
      - "**.ts"
      - ".github/workflows/**"
      - ".vscode/**"
  pull_request:
    branches:
      - master
    paths:
      - "**.ts"
      - ".github/workflows/**"
      - ".vscode/**"
  workflow_dispatch:


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.34.5
          run_install: true

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22.23.2
          cache: pnpm

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint